In [9]:
import numpy as np 

np.random.seed(2)

a = np.random.randint(0, 36,(6,6))
a

array([[15,  8, 22, 18, 11,  7],
       [34, 31, 11, 21, 31, 26],
       [20,  3,  4, 33,  3,  5],
       [24,  4,  6, 31, 19, 31],
       [ 2, 16, 12,  4, 26, 15],
       [ 8, 15,  8, 17, 22,  9]])

In [10]:
#convert into identity 

row = a.shape[0]
col = a.shape[1]

for i in range (row):
    for j in range (col):
        if i == j: 
            a[i,j] = 1
        else:
            a[i,j] = 0

print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [11]:
# alternative using inverse dot product 

a_1 = np.linalg.inv(a)
a = a_1 @ a
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
