1. Create an array of shape (10, 10) with uint8 random values

In [21]:
import numpy as np 

array_1 = np.random.randint(0, 256, (10, 10), dtype = np.uint8) 

print(array_1)

[[126 255 202 254  46  23  48 187  35  27]
 [ 52   1 207 199  89  70  44  63 211 151]
 [177 138  94  44 176 255 166  47  80 223]
 [193 239 175  67  14 194 139 196   2 108]
 [102 203 174 234 173 109 161 209 145 164]
 [ 75  95 196 184 103 115 248   4  89 202]
 [ 11  72  46 177 128 211  70  32  15 145]
 [220 146 247 134  91 255 223 254  41 110]
 [ 48 197 177  39  10  61 191 180 210  16]
 [ 58 117  45  21 249  30 162 193  54  53]]


2. Print the shape, size and dimension

In [22]:
print("array_1 shape: ", array_1.shape)
print()
print("array_1_size: ", array_1.size)
print()
print("array_1_dimension: ", array_1.ndim)

array_1 shape:  (10, 10)

array_1_size:  100

array_1_dimension:  2


3. Compute the sum of the third row to the last row

In [23]:
print(array_1[2 : 10])
print()
total = np.sum(array_1[2 : 10])
print("Total elements from third to last row: ", total)


[[177 138  94  44 176 255 166  47  80 223]
 [193 239 175  67  14 194 139 196   2 108]
 [102 203 174 234 173 109 161 209 145 164]
 [ 75  95 196 184 103 115 248   4  89 202]
 [ 11  72  46 177 128 211  70  32  15 145]
 [220 146 247 134  91 255 223 254  41 110]
 [ 48 197 177  39  10  61 191 180 210  16]
 [ 58 117  45  21 249  30 162 193  54  53]]

Total elements from third to last row:  10451


4. Compute the average of the columns

In [24]:
total_all = np.sum(array_1[:])
print("Total of all elements in array: ", total_all)

average = total_all/np.shape(array_1)[0] # [0] represent no. of columns
print("Average of elements by columns: ", average)

Total of all elements in array:  12741
Average of elements by columns:  1274.1
