In [65]:
def array_properties(a):
    print("array: ", a)
    print("array shape:", a.shape)
    print("array dimension: ", a.ndim)
    print("array datatype: ", a.dtype)
    print("array size: ", a.size)
    print()

In [66]:
#Q1. Create an array of shape (100, 100, 3) of unsigned int

import numpy as np

np.random.seed(12345)

a = np.random.randint(0, 256, (100, 100, 3), dtype = np.uint8)
array_properties(a)

array:  [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
array shape: (100, 100, 3)
array dimension:  3
array datatype:  uint8
array size:  30000



In [67]:
#Q2 Find the values that are less than 30, 50, 100, 250 

a30 = a[a<30]
print("Values less than 30:", a30)

a50 = a[a<50]
print("Values less than 50:", a50)

a100 = a[a<100]
print("Values less than 100:", a100)

a250 = a[a<250]
print("Values less than 100:", a250)

Values less than 30: [29  8 21 ...  5 28 24]
Values less than 50: [45 29  8 ... 35 24 46]
Values less than 100: [81 45 29 ... 75 24 46]
Values less than 100: [226  81 237 ... 156 214 199]


In [68]:
ia30_ = a<30
ia30_ = ia30_ == True 
print(ia30_)
print("Values less than 30:", a[ia30_])

print()

ia50_ = a<50
ia50_ = ia50_ == True 
print(ia50_)
print("Values less than 50:", a[ia50_])

print()

ia100_ = a<100
ia100_ = ia100_ == True 
print(ia100_)
print("Values less than 100:", a[ia100_])

print()

ia250_ = a<250
ia250_ = ia250_ == True 
print(ia250_)
print("Values less than 250:", a[ia250_])


[[[False False False]
  [False False False]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True False  True]]

 [[ True False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [ True False False]
  [False False  True]]

 [[False False False]
  [False False False]
  [ True False  True]
  ...
  [False False False]
  [False  True False]
  [False False False]]

 ...

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]]
Values less than 30: [29  8 21 ...  5 28 24]

[[[False False False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False

In [69]:
#Q3 Split the array into 4 parts vertically and horizontally

a1 = np.hsplit(a, 4)
print(a1)
print(len(a1))
print(type(a1))

[array([[[226,  81, 251],
        [237, 229,  45],
        [225, 227,  29],
        ...,
        [184, 191,  91],
        [ 76, 185,  95],
        [247,  90,  80]],

       [[  5, 116, 247],
        [167,  74, 150],
        [ 36, 229,  76],
        ...,
        [127, 163,  81],
        [199, 213, 119],
        [ 63, 212,  96]],

       [[192,  98, 195],
        [ 57,  77, 233],
        [  7, 230,   8],
        ...,
        [138, 184,  28],
        [ 71,  78, 166],
        [135, 119,  16]],

       ...,

       [[ 61, 149, 122],
        [ 60, 176, 204],
        [102,  45,  44],
        ...,
        [121, 154, 249],
        [ 66, 225,  82],
        [245, 189,  52]],

       [[120,  73, 190],
        [175,  32,  56],
        [211, 192, 194],
        ...,
        [ 76, 190,   0],
        [ 81,  44,  45],
        [ 16, 207, 148]],

       [[212, 239,  76],
        [ 92, 178, 105],
        [ 90, 242, 147],
        ...,
        [ 26,   1,  82],
        [150, 128,  55],
        [ 68,  34,  14]

In [70]:
a1 = np.vsplit(a, 4)
print(a1)
print(len(a1))
print(type(a1))

[array([[[226,  81, 251],
        [237, 229,  45],
        [225, 227,  29],
        ...,
        [152, 224, 239],
        [147, 249, 235],
        [ 22,  77,  13]],

       [[  5, 116, 247],
        [167,  74, 150],
        [ 36, 229,  76],
        ...,
        [ 85, 171, 127],
        [  1, 129, 245],
        [243,  42,  21]],

       [[192,  98, 195],
        [ 57,  77, 233],
        [  7, 230,   8],
        ...,
        [ 64, 151, 156],
        [202,  15, 104],
        [221, 112, 230]],

       ...,

       [[212,  55, 136],
        [170,   5, 151],
        [ 33,   9, 112],
        ...,
        [ 12, 129, 176],
        [125,  51,  68],
        [192,  52, 192]],

       [[ 53, 191, 171],
        [ 74,  77,  83],
        [210, 212, 185],
        ...,
        [220, 249, 114],
        [149,  10,  38],
        [ 60,  40, 179]],

       [[189, 240, 205],
        [ 49,  67, 250],
        [230, 181, 197],
        ...,
        [236,  32, 103],
        [200, 207, 139],
        [188, 209, 251]

In [71]:
#Q4 Copy array from question 1 and change the values that are less than 110 to 0 and others to 255

import numpy as np

np.random.seed(12345)

a = np.random.randint(0, 256, (100, 100, 3), dtype = np.uint8)
print("Array properties a: ")
array_properties(a)

b = a.copy()
print("Array properties b: ")
array_properties(b)



Array properties a: 
array:  [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
array shape: (100, 100, 3)
array dimension:  3
array datatype:  uint8
array size:  30000

Array properties b: 
array:  [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195

In [72]:
b[b<110] = 0
b[b>=110] = 255

In [73]:
print("Array properties a: ")
array_properties(a)

print()

print("Array properties b: ")
array_properties(b)

Array properties a: 
array:  [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
array shape: (100, 100, 3)
array dimension:  3
array datatype:  uint8
array size:  30000


Array properties b: 
array:  [[[255   0 255]
  [255 255   0]
  [255 255   0]
  ...
  [255 255 255]
  [255 255 255]
  [  0   0   0]]

 [[  0 255 255]
  [255   0 255]
  [  0 255   0]
  ...
  [  0 255 255]
  [  0 255 255]
  [255   0   0]]

 [[255   0 25