In [1]:
# create an array a, of shape (6X6) using randint and seed 2 

import numpy as np 

def array_properties(a):
    print("array shape:", a.shape)
    print("array dimension: ", a.ndim)
    print("array datatype: ", a.dtype)
    print("array size: ", a.size)
    print()

np.random.seed(2)

a = np.random.randint(0, 36,(6,6))

print(a)
array_properties(a)

[[15  8 22 18 11  7]
 [34 31 11 21 31 26]
 [20  3  4 33  3  5]
 [24  4  6 31 19 31]
 [ 2 16 12  4 26 15]
 [ 8 15  8 17 22  9]]
array shape: (6, 6)
array dimension:  2
array datatype:  int64
array size:  36



In [2]:
# convert the array a, to an identity matrix I 

row = a.shape[0]
col = a.shape[1]
I = a

for i in range (row):
    for j in range (col):
        if i == j: 
            I[i,j] = 1
        else:
            I[i,j] = 0

print(I)
array_properties(I)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
array shape: (6, 6)
array dimension:  2
array datatype:  int64
array size:  36



In [4]:
row,col = a.shape

I_ = np.copy(a)

for i in range (row):
    for j in range (col):
        if i == j: 
            I[i,j] = 1
        else:
            I[i,j] = 0

print(I_)
array_properties(I_)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
array shape: (6, 6)
array dimension:  2
array datatype:  int64
array size:  36



In [5]:
# alternative using inverse dot product 

a_1 = np.linalg.inv(a)
I_1 = a_1 @ a

print(I_1)
array_properties(I_1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
array shape: (6, 6)
array dimension:  2
array datatype:  float64
array size:  36

