In [1]:
import numpy as np 

array_1 = np.random.randint(0, 256, (10, 10), dtype = np.uint8) 

print(array_1)

[[ 77 217 181 254  63 253 247 225 232  65]
 [ 40  15  75 104 183 246  76 212 152 196]
 [ 51 198 135  13 230 221  55  36 240  65]
 [239 119 233 125 237 231  17 121 152 122]
 [202   4 162  20 219 168 164   1 186 145]
 [ 19 163  71  33 211 223 250 191 164  23]
 [131 117 216 148 112 104 224  31  39  72]
 [146  33 230  59 129 197  65  71 142  93]
 [250 135 110 208  94  62 190  35 151  77]
 [169 247 171 220 213  74  71  96   9 237]]


In [2]:
print("array_1 shape: ", array_1.shape)
print()
print("array_1_size: ", array_1.size)
print()
print("array_1_dimension: ", array_1.ndim)

array_1 shape:  (10, 10)

array_1_size:  100

array_1_dimension:  2


In [3]:
print(array_1[-3])
print()
total = np.sum(array_1[-3])
print("Total elements from the third last row: ", total)

[146  33 230  59 129 197  65  71 142  93]

Total elements from the third last row:  1165


In [6]:
ar_avg = np.mean(array_1, axis=0)
print(ar_avg)

[132.4 124.8 158.4 118.4 169.1 177.9 135.9 101.9 146.7 109.5]
